controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

epo_security:
    resource: '@EpoSecurityBundle/config/routing.yaml'

epo_auth_sso:
    resource: '@EpoAuthSsoBundle/config/routing.yaml'
